### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by duerreda** [toogad/PooPyLab_Project#2]
Hi,

this project has been inactive for the past couple of months. Do you plan to continue working on the implementation and, e.g., to add support for ASM models such as 2d and 3 as well as for dynamic simulations?

Thanks,
David

**Comment by toogad** [comment]
Yes. I have been busy with work recently and didn't have time to update the
project. But it is still alive. If you would like to help, please let me
know.

Thanks.
Kai

On Mon, Sep 14, 2015 at 4:49 AM, duerreda notifications@github.com wrote:

> Hi,
> 
> this project has been inactive for the past couple of months. Do you plan
> to continue working on the implementation and, e.g., to add support for ASM
> models such as 2d and 3 as well as for dynamic simulations?
> 
> Thanks,
> David
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toogad/PooPyLab_Project/issues/2.

## 

Kai Zhang

---

Coincidence is God's way of remaining anonymous.

**Comment by jcramer** [comment]
I am interested in progress/assisting on this project as well. I have implemented ASM1 in matlab and created a c# application which references the matlab/simulink library, but the application is limited to just one plant configuration. I've been wanting to build something similar to this project for quite some time. What next steps are needed?

**Comment by toogad** [comment]
James,

Thank you for being interested in the PooPyLab project. I apologize for not
getting back to you earlier. I have been buried by work lately. You know
how consulting it is, LoL.

Because of travel and routine work, I have not put much effort in the
development recently. But I can briefly tell you where we are:
1. Definitions of main classes: Pipe, ASMReactor, Influent, Effluent, WAS
   etc. I think these should be sufficient for the "frame work" of the
   software before we put more components in for full plant simulation
   purpose. So far the units can be linked to one another and form a PFD.
2. My recent (June 2015) effort focused on figuring out how to determine
   the simulation sequence using the "sequential modular" mode. I have used
   the Strongly Connected Component approach to identify the units that are in
   loops in a PFD (well, one the PFD I tested, more testing should be done).
   The next step on this is to determine how to tear the identified loops and
   form a simulation sequence. I want to at least make sure this works and
   gives good steady state results before adding other things.
3. Other things: GUI, equation based dynamic simulation, etc.

There should be some description in the Readme file on github. And there is
a .dia chart that shows the relatonship among the classes. But some of the
stuff might have changed. I am a environmental consultant and don't keep a
constant update of the repository. I will upload the recent files to github.

I am glad that you have experience in building something similar in MATLAB.
Please feel free to let me know your thoughts. And I think when PooPyLab is
ready to be tested, we can test it and use your MATLAB code to verify.

Regards,

Kai

On Sat, Oct 3, 2015 at 3:28 PM, James Cramer notifications@github.com
wrote:

> I am interested in progress/assisting on this project as well. I have
> implemented ASM1 in matlab and created a c# application which references
> the matlab/simulink library, but the application is limited to just one
> plant configuration. I've been wanting to build something similar to this
> project for quite some time. What next steps are needed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toogad/PooPyLab_Project/issues/2#issuecomment-145286216
> .

## 

Kai Zhang

---

Coincidence is God's way of remaining anonymous.

**Comment by muslumcus** [comment]
Dear Kai,
I use Excel VBA for coding and I've implemented ASM1 and ASM3 already. I'm now working on BioP module for ASM3. All of the tools use dynamic simulation by Runge-Kutta methods. Also, there are two aeration options as constant DO level and constant aeration rate. Besides, it is possible to define external caron source for the reactors. For settling, I use a 10-layer, one dimensional settling model with Takacs' double exponential model. 

What my students ask is the steady-state solution for all my Excel ASM tools, becuase dynamic simulation takes time. I have no experience to obtain a steady-state simulation of ASM. And no idea at all. I tried to see your code but it is in python and its very difficult for me to follow a python code. 

Could you help me about this? A simple flow diagram of what to do step by step for steady-state solution together with the settler.
I have all reactors, links, model parameters, component concentrations in all units, compositions (COD, TKN, TN, TP, TSS) in all units, influent, effluent, and was units assigned in arrays and custom collections. I only nee dthe solution algorithm.

Regards,
Selami

**Comment by toogad** [comment]
Hi Selami,

I am pretty new to coding my own package...

If you already have the code ready for dynamic simulations, you should be able
to get the pseudo steady state fairly easily, I guess.

Here is what I think you may want to try:
1) I assume you have a daily diurnal profile of flows and concentrations per
hour (or something like that if you are dealing with industrial wastewater);

2) Calculate the daily mass of the model component that enters the plant

3) Calculate the average daily flow entering the plant

4) Calculate the average concentrations of the model components using the
results from 2) and 3)

5) Use the result from 3) and 4) as the input for the model and get the pseudo
steady state

Alternatively, I think, you can run the dynamic model with the same diurnal
influent profile for a very long time and take the flow-weighted average of the
output as the steady state result.

Like I said, I am still learning many aspects of modeling and coding. So please
do verify with real experts in these areas.

Good luck.

Regards,
Kai

**Comment by muslumcus** [comment]
Dear Kai,

thanks you for your kind reply. I already developed dynamic simulation tool
for any kind of system configuration from the user. I use RK2, RK3, or RK4
depending on user input. After I wrote you that message, I considered a
simple solution. as follows using RKF45 method
1. Collect user data like min and max step size and convergence criteria.
2. Build an ordinary differential equation for each component in each
reactor using mass balance principle based on bulk flows and reaction rates
3. Calculate RK4 and RK5 parameters for all reactors and components
4. Calculate an updated step size for each component in each reactor
5. Find the minimum value of step sizes calculated in previous step
6. Use the minimum step size found in previous step to calculate all the
component concentrations in all reactors using RK5 formula.
7. Calculate component concentrations in overflow and underflow of settler
8. For each component in each reactor, calculate a convergence criteria.
9. If all are converged, then report the results

This method (I'm now testing it for several user inputs) produces a
steady-state solution at around 5-10 HRT of the system depending on
parameter selection like minimum and maximum step sizes. It really works.
The best side is that you can assign the steady-state solution for all
reactors as the initial values in dynamic simulation, as a result of which
dynamic simulations become more realistic.

Thank you for kindest help, and see you in next project
Selami

toogad <notifications@github.com>, 4 Eki 2019 Cum, 22:12 tarihinde şunu
yazdı:

**Comment by starfriend10** [comment]
Hi Kai,
This is Junjie. I noticed your project two years ago and I couldn't run it at that time. I did a lot research (environmental engineering) using Python, so I suggested one student to develop a Python-based WRRF(WWTP) simulation package since that time. His development is relatively slow, and recently I noticed that you came back and updated many stuffs. However, you deleted the detailed description in the readme file, does it mean that the package is still under development and can't run? Do you mind to share currently how the progress it is and if there is a to-do list? I don't know, but we may help.

**Comment by toogad** [comment]
Hi Junjie,

Thanks for coming back to check on the PooPyLab project.

I made some good progress in the past few months. At the mean time, I am moving
the old README into the wiki. 

For using the current classes/libraries, the wiki has some instructions. Please
check it out and let me know if you got further questions.

Regards,
Kai


On [Mon Oct-28-2019] [02:23:59 AM], starfriend10 wrote:
> Hi Kai,
> This is Junjie. I noticed your project two years ago and I couldn't run it at
> that time. I did a lot research (environmental engineering) using Python, so I
> suggested one student to develop a Python-based WRRF(WWTP) simulation package
> since that time. His development is relatively slow, and recently I noticed
> that you came back and updated many stuffs. However, you deleted the detailed
> description in the readme file, does it mean that the package is still under
> development and can't run? Do you mind to share currently how the progress it
> is and if there is a to-do list? I don't know, but we may help.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*
> 

--
